Studyrecord/Models/ErrorViewModel.cs
using System;

namespace Studyrecord.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Studyrecord/Models/OpintopäiväkirjaContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Studyrecord.Models
{
    public partial class OpintopäiväkirjaContext : DbContext
    {
        public OpintopäiväkirjaContext()
        {
        }

        public OpintopäiväkirjaContext(DbContextOptions<OpintopäiväkirjaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Topic> Topic { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("server=localhost;database=Opintopäiväkirja;trusted_connection=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Topic>(entity =>
            {
                entity.Property(e => e.TopicId).HasColumnName("TopicID");

                entity.Property(e => e.CompletionDate)
                    .HasColumnName("completionDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.Description).HasMaxLength(255);

                entity.Property(e => e.Estimatedtime)
                    .HasColumnName("estimatedtime")
                    .HasColumnType("decimal(18, 0)");

                entity.Property(e => e.Source)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Start).HasColumnType("datetime");

                entity.Property(e => e.TimeSpent).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Studyrecord/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Studyrecord.Models
{
    public partial class Topic
    {
        public int TopicId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal? Estimatedtime { get; set; }
        public decimal? TimeSpent { get; set; }
        public string Source { get; set; }
        [DataType(DataType.Date)]
        public DateTime? Start { get; set; }
        public bool? InProgress { get; set; }
        [DataType(DataType.Date)]
        public DateTime? CompletionDate { get; set; }
    }
}

Studyrecord/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Studyrecord.Models;

namespace Studyrecord.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Show()
        {
            OpintopäiväkirjaContext db = new OpintopäiväkirjaContext();
            var akt = db.Topic.Where(a => a.InProgress == true).ToList();
            return View(akt);
        }
        public ActionResult Search()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Studyrecord/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studyrecord.Models;

namespace Studyrecord.Controllers
{
    public class TopicsController : Controller
    {
        
            OpintopäiväkirjaContext db = new OpintopäiväkirjaContext();
    
        public async Task<IActionResult> Index()
        {
            return View(await db.Topic.ToListAsync());
        }
        public ActionResult Haku(string keyword)
        {
            ViewBag.sana = keyword;
            try
            {
                var haettu = db.Topic.Where(a => a.Title.Contains(keyword)).ToList();
                if (haettu.Count!=0)
                    return View("Index", haettu);
                else
                    return View();
            }


            catch
            {
                return View("Error", new ErrorViewModel());
            }
        }

     
        public IActionResult Create()
        {
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TopicId,Title,Description,Estimatedtime,TimeSpent,Source,Start,InProgress,CompletionDate")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Add(topic);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await db.Topic.FindAsync(id);
            if (topic == null)
            {
                return NotFound();
            }
            return View(topic);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TopicId,Title,Description,Estimatedtime,TimeSpent,Source,Start,InProgress,CompletionDate")] Topic topic)
        {
            if (id != topic.TopicId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(topic);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TopicExists(topic.TopicId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await db.Topic
                .FirstOrDefaultAsync(m => m.TopicId == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var topic = await db.Topic.FindAsync(id);
            db.Topic.Remove(topic);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TopicExists(int id)
        {
            return db.Topic.Any(e => e.TopicId == id);
        }
    }
}

Studyrecord/Views/Home/Index.cshtml
@model List<Studyrecord.Models.Topic>
@{
    ViewData["Title"] = "Home Page";

}
<p>@Html.ActionLink("Show all topics", "Index", "Topics", null, new { @class = "someClass" })</p>
<p>@Html.ActionLink("Show aktive topics", "Show", "Home", null, new{ @class = "someClass" })</p>

<div class="text-center">
    <h1 class="display-4">WELCOME TO HELL</h1>

</div>
<p>@Html.ActionLink("Search from Topics", "Search", "Home")</p>

Studyrecord/Views/Home/Search.cshtml
@{
    ViewData["Title"] = "Search";
}

<h2>Search</h2>
<form method="post" action="@Url.Action("Haku", "Topics")" >
    
       
        Keyword:<br />
        <input type="text" name="keyword" />
   
   
    <div class="form-group">
        <input type="submit" value="search">
    </div>
</form>

Studyrecord/Views/Home/show.cshtml
@model IEnumerable<Studyrecord.Models.Topic>

@{
    ViewData["Title"] = "showaktive";
}

<h2>aktive topics</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estimatedtime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeSpent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InProgress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletionDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estimatedtime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeSpent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Source)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InProgress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompletionDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TopicId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TopicId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TopicId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Studyrecord/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Studyrecord</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Studyrecord - <a asp-area="" asp-controller="Home"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Studyrecord/Views/Topics/Create.cshtml
@model Studyrecord.Models.Topic

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estimatedtime" class="control-label"></label>
                <input asp-for="Estimatedtime" class="form-control" />
                <span asp-validation-for="Estimatedtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSpent" class="control-label"></label>
                <input asp-for="TimeSpent" class="form-control" />
                <span asp-validation-for="TimeSpent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InProgress" class="control-label"></label>
                <input asp-for="InProgress" class="form-control" />
                <span asp-validation-for="InProgress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompletionDate" class="control-label"></label>
                <input asp-for="CompletionDate" class="form-control" />
                <span asp-validation-for="CompletionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Studyrecord/Views/Topics/Delete.cshtml
@model Studyrecord.Models.Topic

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estimatedtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estimatedtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeSpent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeSpent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InProgress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InProgress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompletionDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TopicId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Studyrecord/Views/Topics/Details.cshtml
@model Studyrecord.Models.Topic

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Topic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estimatedtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estimatedtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeSpent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeSpent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InProgress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InProgress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompletionDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TopicId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Studyrecord/Views/Topics/Edit.cshtml
@model Studyrecord.Models.Topic

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TopicId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estimatedtime" class="control-label"></label>
                <input asp-for="Estimatedtime" class="form-control" />
                <span asp-validation-for="Estimatedtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSpent" class="control-label"></label>
                <input asp-for="TimeSpent" class="form-control" />
                <span asp-validation-for="TimeSpent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InProgress" class="control-label"></label>
                <input asp-for="InProgress" class="form-control" />
                <span asp-validation-for="InProgress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompletionDate" class="control-label"></label>
                <input asp-for="CompletionDate" class="form-control" />
                <span asp-validation-for="CompletionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Studyrecord/Views/Topics/Haku.cshtml
@{
    ViewData["Title"] = "Haku";
}

<h2>No results for @ViewBag.sana</h2>
<p>@Html.ActionLink("Search again", "search", "home")</p>

Studyrecord/Views/Topics/Index.cshtml
@model IEnumerable<Studyrecord.Models.Topic>

@{
    ViewData["Title"] = "Index";
}

<h2>TOPICS</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estimatedtime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeSpent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InProgress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletionDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estimatedtime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeSpent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Source)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InProgress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompletionDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TopicId">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.TopicId">Details</a> |*@
                <a asp-action="Delete" asp-route-id="@item.TopicId">Delete</a>
            </td>
        </tr>
}

    </tbody>
</table>
<p>@Html.ActionLink("Search", "search", "home")</p>